// Generates apps/nextblock/lib/setup/migrations-bundle.ts — an embedded copy of the
// forward-only SQL migrations in libs/db/src/supabase/migrations.
//
// Why: the /setup wizard applies the schema by reading those .sql files from disk
// (schema-apply.ts). On a serverless host (Vercel) the function's filesystem does NOT
// contain libs/db, so the on-disk read finds nothing and the auto-apply fails. Embedding
// the SQL as a bundled module makes schema application work everywhere with no reliance on
// file tracing. Local dev and Docker still prefer the on-disk files (always current); the
// bundle is the fallback when the directory isn't present.
//
// Re-run after adding a migration:  npm run generate:migrations-bundle
// (analogous to `npm run generate:sandbox`). The sync:create-nextblock step copies the
// generated bundle into the create-nextblock template.

import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';

const WORKSPACE_ROOT = path.resolve(__dirname, '..', '..');
const MIGRATIONS_DIR = path.join(
  WORKSPACE_ROOT,
  'libs',
  'db',
  'src',
  'supabase',
  'migrations',
);
const OUT_FILE = path.join(
  WORKSPACE_ROOT,
  'apps',
  'nextblock',
  'lib',
  'setup',
  'migrations-bundle.ts',
);

const files = readdirSync(MIGRATIONS_DIR)
  .filter((name) => /^\d+_.*\.sql$/.test(name))
  .sort();

const entries = files.map((name) => ({
  version: name.split('_')[0],
  name,
  sql: readFileSync(path.join(MIGRATIONS_DIR, name), 'utf8'),
}));

const banner =
  '// AUTO-GENERATED by tools/scripts/generate-migrations-bundle.ts — do not edit by hand.\n' +
  '// Regenerate after adding a migration:  npm run generate:migrations-bundle\n' +
  '//\n' +
  '// Embedded forward-only migrations so the /setup wizard can apply the schema on\n' +
  "// serverless hosts (Vercel) where libs/db isn't on the function filesystem.\n\n";

const body =
  'export interface BundledMigration {\n' +
  '  /** Numeric version prefix, e.g. "00000000000030". */\n' +
  '  version: string;\n' +
  '  /** Original migration filename. */\n' +
  '  name: string;\n' +
  '  /** Raw SQL contents. */\n' +
  '  sql: string;\n' +
  '}\n\n' +
  `export const MIGRATIONS_BUNDLE: BundledMigration[] = ${JSON.stringify(entries, null, 2)};\n`;

writeFileSync(OUT_FILE, banner + body, 'utf8');
console.log(`Wrote ${entries.length} migrations -> ${path.relative(WORKSPACE_ROOT, OUT_FILE)}`);
