"use client";

import { ThemeProvider } from "next-themes";

// Suppress the React 19 warning for the <script> tag generated by next-themes in development
if (typeof window !== 'undefined' && process.env.NODE_ENV === 'development') {
  const orig = console.error;
  console.error = (...args: any[]) => {
    if (typeof args[0] === 'string' && args[0].includes('Encountered a script tag')) {
      return;
    }
    orig.apply(console, args);
  };
}
import { AuthProvider } from '../context/AuthContext';
import { LanguageProvider, useLanguage } from '../context/LanguageContext';
import { CurrentContentProvider } from '../context/CurrentContentContext';
import { DeferredCartTranslator } from '../components/DeferredCartTranslator';
import { CurrencyProvider } from '@nextblock-cms/ecommerce/CurrencyProvider';
import { TranslationsProvider } from '@nextblock-cms/utils';

function TranslationBridge({
  children,
  translations,
}: {
  children: React.ReactNode;
  translations: { key: string; translations: Record<string, string> }[];
}) {
  const { currentLocale } = useLanguage();

  return (
    <TranslationsProvider translations={translations} lang={currentLocale}>
      {children}
    </TranslationsProvider>
  );
}

export function Providers({ children, ...props }: { children: React.ReactNode;[key: string]: any; }) {
  const {
    serverUser,
    serverProfile,
    serverLocale,
    initialCurrencies,
    initialCurrencyCode,
    initialAvailableLanguages,
    initialDefaultLanguage,
    translations,
    nonce
  } = props;

  return (
    <AuthProvider serverUser={serverUser} serverProfile={serverProfile}>
      <LanguageProvider
        serverLocale={serverLocale}
        initialAvailableLanguages={initialAvailableLanguages}
        initialDefaultLanguage={initialDefaultLanguage}
      >
        <CurrencyProvider
          initialCurrencies={initialCurrencies}
          initialCurrencyCode={initialCurrencyCode}
          locale={serverLocale}
        >
          <CurrentContentProvider>
            <DeferredCartTranslator />
            <TranslationBridge translations={translations}>
              <ThemeProvider
                attribute="class"
                defaultTheme="light"
                enableSystem
                disableTransitionOnChange
                nonce={nonce}
                themes={['light', 'dark', 'vibrant']}
              >
                {children}
              </ThemeProvider>
            </TranslationBridge>
          </CurrentContentProvider>
        </CurrencyProvider>
      </LanguageProvider>
    </AuthProvider>
  );
}
